---
aircraft: Toliss A321neo
description: Configuration parameters for Streamdeck 32 keys
version: 1.0.0
last-updated: 03-APR-2024
#
# CHANGELOG
#
# 1.0.0  03-APR-2023  Initial version
#
# LAYOUT
#
default-label-size: 12
default-label-font: DIN Medium.ttf
default-annunciator-style: v
# home-page-name: xplane
