default-label-color: white
default-label-font: D-DIN.otf
default-label-size: 13
default-text-size: 24
default-label-position: ct
default-homepage-name: main
home-page-name: main
default-icon-color: (94, 111, 130)
