# Copyright (c) 2016-2024 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Cockpitdecks Configs
site_url: https://dlicudi.github.io/cockpitdecks-configs/
site_author: Duane Licudi
site_description: >-
  A set of aircraft cockpit configs for Cockpitdecks

# Repository
repo_name: dlicudi/cockpitdecks-configs
repo_url: https://github.com/dlicudi/cockpitdecks-configs
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Requirements: getting-started/requirements.md
      - Development: getting-started/development.md
  - Decks:
      - Overview: decks/index.md
      - Aerobask Robin DR401: decks/aerobask-robin-dr401.md
      - Beechcraft Baron 58: decks/beechcraft-baron-58.md
      - Cessna 172 SP: decks/cessna-172-sp.md
      - Cirrus SR22:
          - Overview: decks/cirrus-sr22.md
          - Loupedeck Live:
              - Overview: decks/cirrus-sr22/loupedecklive1/index.md
              - Home: decks/cirrus-sr22/loupedecklive1/home.md
              - PFI: decks/cirrus-sr22/loupedecklive1/pfi.md
              - Switches: decks/cirrus-sr22/loupedecklive1/switches.md
              - FCU: decks/cirrus-sr22/loupedecklive1/fcu.md
              - Engine: decks/cirrus-sr22/loupedecklive1/engine.md
              - Pedestal: decks/cirrus-sr22/loupedecklive1/pedestal.md
              - Radio: decks/cirrus-sr22/loupedecklive1/radio.md
              - Transponder: decks/cirrus-sr22/loupedecklive1/transponder.md
              - GCU478: decks/cirrus-sr22/loupedecklive1/gcu478.md
              - Views: decks/cirrus-sr22/loupedecklive1/views.md
              - Weather: decks/cirrus-sr22/loupedecklive1/weather.md
      - Embraer E-Jets Family: decks/embraer-e-jets-family.md
      - Lancair Evolution:
          - Overview: decks/lancair-evolution.md
          - Loupedeck Live:
              - Overview: decks/lancair-evolution/loupedecklive1/index.md
              - Audio Panel: decks/lancair-evolution/loupedecklive1/audiopanel.md
              - Engine: decks/lancair-evolution/loupedecklive1/engine.md
              - FCU: decks/lancair-evolution/loupedecklive1/fcu.md
              - G1000: decks/lancair-evolution/loupedecklive1/g1000.md
              - Home: decks/lancair-evolution/loupedecklive1/home.md
              - Pedestal: decks/lancair-evolution/loupedecklive1/pedestal.md
              - PFI: decks/lancair-evolution/loupedecklive1/pfi.md
              - Radio: decks/lancair-evolution/loupedecklive1/radio.md
              - Switches: decks/lancair-evolution/loupedecklive1/switches.md
              - Switches 2: decks/lancair-evolution/loupedecklive1/switches2.md
              - Transponder: decks/lancair-evolution/loupedecklive1/transponder.md
              - Views: decks/lancair-evolution/loupedecklive1/views.md
              - Weather: decks/lancair-evolution/loupedecklive1/weather.md
          - Stream Deck XL:
              - Overview: decks/lancair-evolution/streamdeckxl1/index.md
              - Audio Panel: decks/lancair-evolution/streamdeckxl1/audiopanel.md
              - Engine: decks/lancair-evolution/streamdeckxl1/engine.md
              - FCU: decks/lancair-evolution/streamdeckxl1/fcu.md
              - G1000: decks/lancair-evolution/streamdeckxl1/g1000.md
              - PFI: decks/lancair-evolution/streamdeckxl1/pfi.md
              - Radio: decks/lancair-evolution/streamdeckxl1/radio.md
              - Switches: decks/lancair-evolution/streamdeckxl1/switches.md
              - Transponder: decks/lancair-evolution/streamdeckxl1/transponder.md
              - Views: decks/lancair-evolution/streamdeckxl1/views.md
              - Weather: decks/lancair-evolution/streamdeckxl1/weather.md
      - ToLiss Airbus A320 NEO: decks/toliss-airbus-A320-neo.md
      - ToLiss Airbus A321 NEO: decks/toliss-airbus-A321-neo.md
      - ToLiss Airbus A330 NEO: decks/toliss-airbus-a330-neo.md
      - Van's Aircraft RV-10: decks/vans-aircraft-rv-10.md
  - Reference:
      - Overview: reference/index.md
      - Compatibility: reference/compatibility.md
      - Deck Types: reference/deck-types.md
      - Modules:
          - Overview: modules/modules.md
          - Audio Panel: modules/audio-panel.md
          - Engine: modules/engine.md
          - G1000: modules/g1000.md
          - Radio: modules/radio.md
          - Views: modules/views.md
          - Weather: modules/weather.md
      - Tags: reference/tags.md

not_in_nav: |
  examples/*
  experimental/*
  generated/*

# Copyright
copyright: Copyright &copy; 2023 - 2024 Duane Licudi

# Configuration
theme:
  name: material

  # custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.path
    - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
    annotation: material/plus-circle-outline
    tag:
      default: material/tag-outline
      ga: material/airplane
      airliner: material/airplane-takeoff
      loupedeck: material/dialpad
      g1000: material/navigation-variant-outline
      toliss: material/airplane-marker


# Plugins
plugins:
  - social
  - optimize:
      enabled: !ENV [CI, false]
  - tags:
      tags_allowed:
        - GA
        - Airliner
        - Loupedeck
        - G1000
        - ToLiss
        - Work in Progress
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - minify:
  #     minify_html: true

# Hooks
# hooks:
#   - material/overrides/hooks/shortcodes.py
#   - material/overrides/hooks/translations.py

# Additional configuration
extra:
  # version:
  #   provider: mike
  status:
    new: Recently added
    deprecated: Deprecated
  # analytics:
  #   provider: google
  #   property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dlicudi
  tags:
    GA: ga
    Airliner: airliner
    Loupedeck: loupedeck
    G1000: g1000
    ToLiss: toliss
    # - icon: fontawesome/brands/docker
    #   link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    # - icon: fontawesome/brands/python
    #   link: https://pypi.org/project/mkdocs-material/
    # - icon: fontawesome/brands/mastodon
    #   link: https://fosstodon.org/@squidfunk
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/squidfunk

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - material.extensions.preview:
      configurations:
        - sources:
            include:
              - decks/cirrus-sr22.md
              - decks/cirrus-sr22/**
          targets:
            include:
              - decks/cirrus-sr22/**
  - pymdownx.snippets:
      base_path:
        - .
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde



extra_css:
  - stylesheets/extra.css
