# Project information
site_name: Cockpitdecks Configs
site_url: https://dlicudi.github.io/cockpitdecks-configs/
site_author: Duane Licudi
site_description: >-
  A set of aircraft cockpit configs for Cockpitdecks

# Repository
repo_name: GitHub
repo_url: https://github.com/dlicudi/cockpitdecks-configs
edit_uri: blob/main/docs/

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Development: getting-started/development.md
  - Architecture:
      - Overview: architecture/index.md
  - Decks:
      - Robin DR401: decks/aerobask-robin-dr401/index.md
      - Beechcraft Baron 58: decks/beechcraft-baron-58/index.md
      - Cessna 172 SP: decks/cessna-172-sp/index.md
      - Cirrus SR22: decks/cirrus-sr22/index.md
      - Embraer E-Jets Family: decks/embraer-e-jets-family/index.md
      - Lancair Evolution: decks/lancair-evolution/index.md
      - Airbus A320neo: decks/toliss-airbus-a320-neo/index.md
      - Toliss A321neo: decks/toliss-airbus-a321-neo/index.md
      - ToLiss A330neo: decks/toliss-airbus-a330-neo/index.md
      - Van's Aircraft RV-10: decks/vans-aircraft-rv-10/index.md
  - Reference:
      - Overview: reference/index.md
      - Compatibility: reference/compatibility.md
      - Deck Types: reference/deck-types.md
      - Plugin Interface: reference/plugin-interface.md
      - Cirrus SR22 Gaps: reference/cirrus-sr22-gaps.md
      - Modules: modules/modules.md

not_in_nav: |
  examples/*
  experimental/*
  generated/*
  reference/tags.md
  includes/*

# Copyright
copyright: Copyright &copy; 2023 - 2024 Duane Licudi

# Configuration
theme:
  name: readthedocs

# Plugins
plugins:
  - search
  - glightbox

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: dlicudi
      repo: cockpitdecks-configs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path:
        - .
      check_paths: true
      auto_append:
        - docs/includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css
