---
aircraft: Toliss A321neo
description: FCU simulator for Loupedeck Live
version: 1.0.0
last-updated: 03-APR-2024
#
# CHANGELOG
#
# 1.0.0  03-APR-2023  Initial version
#
# LAYOUT
#
home-page-name: fcu
