aircraft: Embraer E-Jets Family
decks:
- name: XPLive1
  brightness: 70
  layout: loupedecklive1
  type: LoupedeckLive
- name: XPLive2
  brightness: 70
  layout: streamdeckxl1
  type: Stream Deck XL
# - layout: loupedecklive1
#   name: Vdeck1
#   type: Virtual LoupedeckLive
- name: e190.overhead.v2
  type: e190.overhead.v2
  layout: overhead
description: Decks
icao: E170
model: E170, E175, E190, E195


dataref-fetch-frequencies:
  sim/cockpit2/gauges/indicators/airspeed_kts_pilot: 1
  sim/cockpit2/gauges/indicators/altitude_ft_pilot: 1
  sim/flightmodel/position/longitude: 1
