---
aircraft: ToLiss A339
description: Configuration parameters for Streamdeck 15 keys
version: 1.0.1
last-updated: 31-OCT-2024
#
# CHANGELOG
#
# 1.0.1: 31-OCT-2024: Initial release (adapted from ToLiss A321)
# 1.0.0  03-APR-2023  Initial version
#
# LAYOUT
#
default-annunciator-style: k
# Special modifications for dark/night
dark-default-label-color: gold
default-label-color: gold
home-page-name: ECAM
