---
aircraft: ToLiss A339
description: Configuration parameters for X-Touch mini
version: 1.0.0
last-updated: 31-OCT-2024
#
# CHANGELOG
#
# 1.0.0: 31-OCT-2024: Initial release (adapted from ToLiss A321)
#
# LAYOUT
#
home-page-name: fcu