# This is at layout level
cockpit-color: (64, 64, 64)
default-label-color: black
default-label-font: D-DIN.otf
default-label-size: 9
default-text-size: 24
default-label-position: ct
home-page-name: index
default-vibrate: SHORT
default-icon-color: (94, 111, 130)
default-annunciator-style: v
default-light-off-intensity: 8
_docs:
  fixture: scripts/fixtures/cirrus-sr22-cruise.yaml
  style: deck-map
  exclude_pages:
    - icing
    - lights
    - switches2
