#!/usr/bin/env python3
"""Regenerate SR22 page-only preview images and generated markdown fragments."""

from __future__ import annotations

import subprocess
from pathlib import Path
import tempfile
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
AIRCRAFT_DOCS = ROOT / "decks" / "cirrus-sr22" / "deckconfig" / "_docs.yaml"
DECK_CONFIG = ROOT / "decks" / "cirrus-sr22" / "deckconfig" / "config.yaml"
LAYOUT_NAME = "loupedecklive1"
LAYOUT_DIR = ROOT / "decks" / "cirrus-sr22" / "deckconfig" / "loupedecklive1"
FIXTURE = ROOT / "scripts" / "fixtures" / "cirrus-sr22-cruise.yaml"
IMAGE_DIR = ROOT / "docs" / "assets" / "images" / "cirrus-sr22" / "generated"
DOC_DIR = ROOT / "docs" / "generated" / "cirrus-sr22" / LAYOUT_NAME
LEGACY_DOC_DIR = ROOT / "docs" / "generated" / "cirrus-sr22"
PAGES_DIR = ROOT / "docs" / "decks" / "cirrus-sr22" / LAYOUT_NAME
LAYOUT_OVERVIEW_PAGE = PAGES_DIR / "index.md"
IMAGE_PAGES = (
    "index",
    "pfi",
    "switches",
    "fcu",
    "engine",
    "pedestal",
    "radio",
    "transponder",
    "gcu478",
    "views",
    "weather",
)
DOC_PAGES = IMAGE_PAGES
LAYOUT_OVERVIEW_MD = DOC_DIR / "index.auto.md"
PAGE_DISPLAY_TITLES = {
    "index": "Home",
    "pfi": "PFI",
    "switches": "Switches",
    "fcu": "FCU",
    "engine": "Engine",
    "pedestal": "Pedestal",
    "radio": "Radio",
    "transponder": "Transponder",
    "gcu478": "GCU478",
    "views": "Views",
    "weather": "Weather",
}


def run(args: list[str]) -> None:
    subprocess.run(args, check=True, cwd=ROOT)


def load_yaml(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a YAML mapping")
    return data


def humanize_deck_type(value: str) -> str:
    mapping = {
        "LoupedeckLive": "Loupedeck Live",
        "Stream Deck XL": "Stream Deck XL",
        "StreamDeckXL": "Stream Deck XL",
    }
    if value in mapping:
        return mapping[value]
    text = value.replace("-", " ").replace("_", " ").strip()
    if not text:
        return value
    text = text.replace("Deck", " Deck").replace("Live", " Live").replace("XL", " XL")
    return " ".join(text.split())


def layout_title(deck_config: dict[str, Any], layout_name: str) -> str:
    for entry in deck_config.get("decks", []):
        if isinstance(entry, dict) and str(entry.get("layout", "")).strip() == layout_name:
            deck_type = str(entry.get("type") or "").strip()
            if deck_type:
                return humanize_deck_type(deck_type)
            deck_name = str(entry.get("name") or "").strip()
            if deck_name:
                return deck_name
    return layout_name


def page_title(page_config: dict[str, Any], page_name: str, page_name_map: dict[str, str]) -> str:
    description = str(page_config.get("description") or "").strip()
    if description:
        return description
    return PAGE_DISPLAY_TITLES.get(page_name, page_name_map[page_name].replace("-", " ").title())


def build_layout_overview_markdown(aircraft_docs: dict[str, Any], layout_title: str, page_docs: list[dict[str, str]]) -> str:
    aircraft = aircraft_docs.get("aircraft", {})
    summary = f"{layout_title} layout for {aircraft.get('title', 'Cirrus SR22')}."

    lines = [
        "<!-- generated by scripts/generate_sr22_docs.py; do not edit directly -->",
        "",
        f"# {layout_title}",
        "",
        summary,
        "",
        "## Deck Map",
        "",
        '<div class="cdx-deck">',
    ]

    for page in page_docs:
        lines.extend(
            [
                f'  <a class="cdx-deck__key" href="{page["href"]}" data-preview>',
                f'    <img src="{page["image"]}" alt="{page["title"]} page preview" />',
                f'    <span>{page["title"]}</span>',
                "  </a>",
            ]
        )

    lines.extend(["</div>", ""])
    return "\n".join(lines).rstrip() + "\n"


def build_page_shell(layout_title: str, title: str, output_name: str, body: str) -> str:
    return (
        f"---\n"
        f"title: {layout_title} {title}\n"
        f"---\n\n"
        f"# {title}\n\n"
        f'<div id="sr22-{LAYOUT_NAME}-{output_name}-preview"></div>\n\n'
        f"{body.lstrip()}"
    )


def build_layout_overview_shell(body: str) -> str:
    lines = [
        "---",
        "icon: material/dialpad",
        "---",
        "",
        body.rstrip(),
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    IMAGE_DIR.mkdir(parents=True, exist_ok=True)
    DOC_DIR.mkdir(parents=True, exist_ok=True)
    PAGES_DIR.mkdir(parents=True, exist_ok=True)
    for stale in LEGACY_DOC_DIR.glob("*.auto.md"):
        stale.unlink()
    aircraft_docs = load_yaml(AIRCRAFT_DOCS)
    deck_config = load_yaml(DECK_CONFIG)
    layout_name_title = layout_title(deck_config, LAYOUT_NAME)

    with tempfile.TemporaryDirectory(prefix="sr22-previews-") as temp_dir:
        temp_image_dir = Path(temp_dir)
        render_args = [
            "python3",
            "scripts/render_deck_preview.py",
            "--layout-dir",
            str(LAYOUT_DIR),
            "--fixture",
            str(FIXTURE),
            "--output-dir",
            str(temp_image_dir),
        ]
        for page in IMAGE_PAGES:
            render_args.extend(["--page", page])
        run(render_args)

        expected_images: set[str] = set()
        for page in IMAGE_PAGES:
            source = temp_image_dir / f"{page}.png"
            target = IMAGE_DIR / f"{page}.page.png"
            expected_images.add(target.name)
            target.write_bytes(source.read_bytes())

    page_name_map = {
        "index": "home",
        "pfi": "pfi",
        "switches": "switches",
        "fcu": "fcu",
        "engine": "engine",
        "pedestal": "pedestal",
        "radio": "radio",
        "transponder": "transponder",
        "gcu478": "gcu478",
        "views": "views",
        "weather": "weather",
    }

    for stale in IMAGE_DIR.glob("*.page.png"):
        if stale.name not in expected_images:
            stale.unlink()

    for page in DOC_PAGES:
        output_name = page_name_map[page]
        run(
            [
                "python3",
                "scripts/generate_page_doc.py",
                "--layout-dir",
                str(LAYOUT_DIR),
                "--fixture",
                str(FIXTURE),
                "--page",
                page,
                "--image-path",
                f"../../../assets/images/cirrus-sr22/generated/{page}.page.png",
                "--output-md",
                str(DOC_DIR / f"{output_name}.auto.md"),
            ]
        )

    page_docs: list[dict[str, str]] = []
    for page in IMAGE_PAGES:
        page_config = load_yaml(LAYOUT_DIR / f"{page}.yaml")
        page_label = page_title(page_config, page, page_name_map)
        output_name = page_name_map[page]
        page_docs.append(
            {
                "title": page_label,
                "href": f"{output_name}/#sr22-{LAYOUT_NAME}-{output_name}-preview",
                "image": f"../../../assets/images/cirrus-sr22/generated/{page}.page.png",
            }
        )

        page_body = (DOC_DIR / f"{output_name}.auto.md").read_text(encoding="utf-8")
        (PAGES_DIR / f"{output_name}.md").write_text(
            build_page_shell(layout_name_title, page_label, output_name, page_body),
            encoding="utf-8",
        )

    overview_body = build_layout_overview_markdown(aircraft_docs, layout_name_title, page_docs)
    LAYOUT_OVERVIEW_MD.write_text(overview_body, encoding="utf-8")
    LAYOUT_OVERVIEW_PAGE.write_text(build_layout_overview_shell(overview_body), encoding="utf-8")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
