#!/usr/bin/env python3
"""Generate a markdown fragment for a deck page from config plus fixture data."""

from __future__ import annotations

import argparse
from pathlib import Path

from render_deck_preview import PreviewRenderer


ROOT = Path(__file__).resolve().parents[1]
REPO_BLOB_BASE = "https://github.com/dlicudi/cockpitdecks-configs/blob/main"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--layout-dir", type=Path, required=True)
    parser.add_argument("--decktype", type=Path, default=ROOT / "decktypes" / "Loupedeck Live.yaml")
    parser.add_argument("--fixture", type=Path)
    parser.add_argument("--page", required=True)
    parser.add_argument("--image-path", required=True, help="Docs-relative image path used in markdown")
    parser.add_argument("--output-md", type=Path, required=True)
    return parser.parse_args()


def repo_blob_url(path: Path) -> str:
    return f"{REPO_BLOB_BASE}/{path.relative_to(ROOT).as_posix()}"


def build_markdown(renderer: PreviewRenderer, page_name: str, image_path: str, layout_dir: Path) -> str:
    page = renderer._load_page(page_name)
    page_path = layout_dir / f"{page_name}.yaml"
    includes = [part.strip() for part in str(page.get("includes", "")).split(",") if part.strip()]

    lines = [
        "<!-- generated by scripts/generate_page_doc.py; do not edit directly -->",
        "",
        f"![{page_name.upper()} preview]({image_path})",
        "",
        "## Source",
        "",
        f'[:material-github: Page config]({repo_blob_url(page_path)})',
    ]

    if includes:
        include_links: list[str] = []
        for include in includes:
            include_path = layout_dir / f"{include}.yaml"
            if include_path.exists():
                include_links.append(f'[:material-source-branch: `{include}.yaml`]({repo_blob_url(include_path)})')
            else:
                include_links.append(f"`{include}.yaml`")
        lines.extend(["", "Includes: " + " · ".join(include_links)])

    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    renderer = PreviewRenderer(args.layout_dir, args.decktype, args.fixture)
    markdown = build_markdown(renderer, args.page, args.image_path, args.layout_dir)
    args.output_md.parent.mkdir(parents=True, exist_ok=True)
    args.output_md.write_text(markdown, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
