source 'https://rubygems.org'

gem "jekyll", "~> 4.3.3" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "just-the-docs", "0.8.1" # pinned to the current release
# gem "just-the-docs"        # always download the latest release

gem "jekyll-seo-tag", "~> 2.8"

gem "jekyll-github-metadata", "~> 2.16"

gem "jekyll-include-cache", "~> 0.2.1"
