name: ci
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ci.yml
      - mkdocs.yml
      - docs/**
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-glightbox pymdown-extensions
      - run: mkdocs gh-deploy --force
